// ========== ENHANCED QUESTION BANK ==========
// Comprehensive question library for all interview categories
// Total: 300+ questions across 6 categories (50+ per category)

const enhancedQuestionBank = {
  hr: [
    // Basic HR Questions (1-15)
    { id: 'hr_1', text: 'Tell me about yourself and your professional background.' },
    { id: 'hr_2', text: 'What are your greatest strengths as a professional?' },
    { id: 'hr_3', text: 'What are your weaknesses and how are you working to improve them?' },
    { id: 'hr_4', text: 'Where do you see yourself in 5 years?' },
    { id: 'hr_5', text: 'Why are you interested in this position?' },
    { id: 'hr_6', text: 'Tell me about a time you faced a challenge at work and how you handled it.' },
    { id: 'hr_7', text: 'Describe a situation where you had to work with a difficult team member.' },
    { id: 'hr_8', text: 'What is your approach to learning new technologies and skills?' },
    { id: 'hr_9', text: 'How do you prioritize your work when you have multiple deadlines?' },
    { id: 'hr_10', text: 'Tell me about your most significant achievement in your career.' },
    { id: 'hr_11', text: 'How do you handle failure and setbacks?' },
    { id: 'hr_12', text: 'What motivates you in your work?' },
    { id: 'hr_13', text: 'Describe your ideal work environment and company culture.' },
    { id: 'hr_14', text: 'How do you stay updated with industry trends and developments?' },
    { id: 'hr_15', text: 'Tell me about a project you led from start to finish.' },
    // Leadership & Teamwork (16-30)
    { id: 'hr_16', text: 'How do you approach problem-solving in your work?' },
    { id: 'hr_17', text: 'Describe a time when you had to adapt to a significant change.' },
    { id: 'hr_18', text: 'What skills do you want to develop further?' },
    { id: 'hr_19', text: 'Tell me about a time you received critical feedback and how you responded.' },
    { id: 'hr_20', text: 'Why should we hire you over other candidates?' },
    { id: 'hr_21', text: 'How do you define success in your career?' },
    { id: 'hr_22', text: 'Tell me about your experience working in cross-functional teams.' },
    { id: 'hr_23', text: 'What is your approach to communication with colleagues and stakeholders?' },
    { id: 'hr_24', text: 'Describe a time when you had to make a difficult decision at work.' },
    { id: 'hr_25', text: 'How do you balance work and personal life?' },
    { id: 'hr_26', text: 'Tell me about a time you had to handle multiple projects simultaneously.' },
    { id: 'hr_27', text: 'How do you handle disagreement with your manager or colleague?' },
    { id: 'hr_28', text: 'Describe your experience mentoring or training others.' },
    { id: 'hr_29', text: 'What is your experience with agile or scrum methodologies?' },
    { id: 'hr_30', text: 'Tell me about a time you went above and beyond your job responsibilities.' },
    // Conflict & Problem Solving (31-45)
    { id: 'hr_31', text: 'How do you handle stress and pressure at work?' },
    { id: 'hr_32', text: 'Describe a situation where you had to meet a tight deadline.' },
    { id: 'hr_33', text: 'Tell me about a time you made a mistake and how you handled it.' },
    { id: 'hr_34', text: 'How do you stay motivated when working on routine tasks?' },
    { id: 'hr_35', text: 'Describe your experience working with different personality types.' },
    { id: 'hr_36', text: 'Tell me about a conflict you resolved in your team.' },
    { id: 'hr_37', text: 'How do you contribute to a positive workplace culture?' },
    { id: 'hr_38', text: 'Describe your experience with performance reviews and feedback.' },
    { id: 'hr_39', text: 'Tell me about a time you had to influence others without formal authority.' },
    { id: 'hr_40', text: 'How do you handle criticism and negative feedback?' },
    { id: 'hr_41', text: 'Describe your experience with client-facing roles.' },
    { id: 'hr_42', text: 'Tell me about a time you had to work under uncertain circumstances.' },
    { id: 'hr_43', text: 'How do you approach goal-setting and achieving targets?' },
    { id: 'hr_44', text: 'Describe your experience with documentation and process improvement.' },
    { id: 'hr_45', text: 'Tell me about your career aspirations and how this role helps you grow.' },
    // Advanced HR (46-55)
    { id: 'hr_46', text: 'How do you measure your own performance and success?' },
    { id: 'hr_47', text: 'Describe a time you had to learn something completely new.' },
    { id: 'hr_48', text: 'Tell me about your experience with remote work.' },
    { id: 'hr_49', text: 'How do you handle being the new person on a team?' },
    { id: 'hr_50', text: 'Describe your experience with interdepartmental collaboration.' },
    { id: 'hr_51', text: 'Tell me about a time you had to present or communicate to senior leadership.' },
    { id: 'hr_52', text: 'How do you stay organized and manage your time effectively?' },
    { id: 'hr_53', text: 'Describe your experience with budget management or financial responsibility.' },
    { id: 'hr_54', text: 'Tell me about a time you had to mentor a struggling team member.' },
    { id: 'hr_55', text: 'How do you view your role in contributing to company success?' },
  ],

  technical: [
    // Web Development Basics (1-15)
    { id: 'tech_1', text: 'Explain the difference between REST API and GraphQL.' },
    { id: 'tech_2', text: 'What is the difference between HTTP and HTTPS?' },
    { id: 'tech_3', text: 'How does the browser rendering engine work?' },
    { id: 'tech_4', text: 'What is the difference between synchronous and asynchronous programming?' },
    { id: 'tech_5', text: 'Explain what CORS is and why it is important.' },
    { id: 'tech_6', text: 'What is the difference between let, const, and var in JavaScript?' },
    { id: 'tech_7', text: 'Explain promises and async/await in JavaScript.' },
    { id: 'tech_8', text: 'What is the event loop in JavaScript?' },
    { id: 'tech_9', text: 'Explain closure in JavaScript with an example.' },
    { id: 'tech_10', text: 'What is hoisting in JavaScript?' },
    { id: 'tech_11', text: 'Explain prototypal inheritance in JavaScript.' },
    { id: 'tech_12', text: 'What are higher-order functions in JavaScript?' },
    { id: 'tech_13', text: 'Explain the difference between == and === in JavaScript.' },
    { id: 'tech_14', text: 'What is the DOM and how do you manipulate it?' },
    { id: 'tech_15', text: 'Explain event delegation in JavaScript.' },
    // Database & Backend (16-30)
    { id: 'tech_16', text: 'What is the difference between SQL and NoSQL databases?' },
    { id: 'tech_17', text: 'Explain normalization in database design.' },
    { id: 'tech_18', text: 'What are database indexes and why are they important?' },
    { id: 'tech_19', text: 'Explain the concept of ACID transactions.' },
    { id: 'tech_20', text: 'What is database sharding and how does it work?' },
    { id: 'tech_21', text: 'Explain the difference between primary and foreign keys.' },
    { id: 'tech_22', text: 'What are common database design patterns?' },
    { id: 'tech_23', text: 'Explain the N+1 query problem and how to solve it.' },
    { id: 'tech_24', text: 'What is caching and how is it implemented?' },
    { id: 'tech_25', text: 'Explain the difference between horizontal and vertical scaling.' },
    { id: 'tech_26', text: 'What is a microservice architecture?' },
    { id: 'tech_27', text: 'Explain the concept of containerization with Docker.' },
    { id: 'tech_28', text: 'What is Kubernetes and its main components?' },
    { id: 'tech_29', text: 'Explain CI/CD pipelines and their importance.' },
    { id: 'tech_30', text: 'What is the difference between monolithic and microservice architectures?' },
    // Security & Performance (31-45)
    { id: 'tech_31', text: 'What is SQL injection and how do you prevent it?' },
    { id: 'tech_32', text: 'Explain cross-site scripting (XSS) and how to prevent it.' },
    { id: 'tech_33', text: 'What is CSRF and how can it be mitigated?' },
    { id: 'tech_34', text: 'Explain OAuth2 and OpenID Connect.' },
    { id: 'tech_35', text: 'What is JWT and how does it work?' },
    { id: 'tech_36', text: 'Explain the concept of rate limiting.' },
    { id: 'tech_37', text: 'What are common web performance optimization techniques?' },
    { id: 'tech_38', text: 'Explain lazy loading and code splitting.' },
    { id: 'tech_39', text: 'What is CDN and how does it improve performance?' },
    { id: 'tech_40', text: 'Explain gzip compression and its benefits.' },
    { id: 'tech_41', text: 'What is minification and why is it important?' },
    { id: 'tech_42', text: 'Explain the critical rendering path.' },
    { id: 'tech_43', text: 'What is server-side rendering vs client-side rendering?' },
    { id: 'tech_44', text: 'Explain the concept of load balancing.' },
    { id: 'tech_45', text: 'What is stateless and stateful architecture?' },
    // Advanced Topics (46-55)
    { id: 'tech_46', text: 'Explain the concept of reactive programming.' },
    { id: 'tech_47', text: 'What is functional programming and its benefits?' },
    { id: 'tech_48', text: 'Explain the observer pattern in software design.' },
    { id: 'tech_49', text: 'What is dependency injection and why is it useful?' },
    { id: 'tech_50', text: 'Explain message queues and their use cases.' },
    { id: 'tech_51', text: 'What is API versioning and common strategies?' },
    { id: 'tech_52', text: 'Explain the concept of webhooks.' },
    { id: 'tech_53', text: 'What is the strangler fig pattern for refactoring?' },
    { id: 'tech_54', text: 'Explain the concept of eventual consistency.' },
    { id: 'tech_55', text: 'What are common design patterns in software development?' },
  ],

  dsa: [
    // Arrays & Strings (1-15)
    { id: 'dsa_1', text: 'Explain the difference between arrays and linked lists. When would you use each?' },
    { id: 'dsa_2', text: 'Write pseudocode for binary search and explain its time complexity.' },
    { id: 'dsa_3', text: 'What are the differences between stacks and queues? Provide examples of use cases.' },
    { id: 'dsa_4', text: 'Explain hash tables and hash collisions. How do you handle collisions?' },
    { id: 'dsa_5', text: 'What is the difference between depth-first search (DFS) and breadth-first search (BFS)?' },
    { id: 'dsa_6', text: 'Explain the concept of dynamic programming and give an example problem.' },
    { id: 'dsa_7', text: 'What is a balanced binary search tree? Why is balancing important?' },
    { id: 'dsa_8', text: 'Describe the quicksort algorithm and analyze its time complexity.' },
    { id: 'dsa_9', text: 'What is the difference between merge sort and quicksort?' },
    { id: 'dsa_10', text: 'Explain the concept of greedy algorithms with an example.' },
    { id: 'dsa_11', text: 'What is a graph? Describe different graph representations.' },
    { id: 'dsa_12', text: 'How would you detect a cycle in a linked list?' },
    { id: 'dsa_13', text: 'Explain the concept of memoization in dynamic programming.' },
    { id: 'dsa_14', text: 'What is the difference between stable and unstable sorting algorithms?' },
    { id: 'dsa_15', text: 'How would you find the longest common subsequence between two strings?' },
    // Sorting & Searching (16-30)
    { id: 'dsa_16', text: 'Explain the concept of Big O notation and provide examples.' },
    { id: 'dsa_17', text: 'What is a trie data structure and what are its use cases?' },
    { id: 'dsa_18', text: 'How would you implement a LRU (Least Recently Used) cache?' },
    { id: 'dsa_19', text: 'Describe Dijkstra\'s algorithm and its applications.' },
    { id: 'dsa_20', text: 'What is the difference between a heap and a binary search tree?' },
    { id: 'dsa_21', text: 'How would you find the kth largest element in an array?' },
    { id: 'dsa_22', text: 'Explain the concept of topological sorting and its applications.' },
    { id: 'dsa_23', text: 'What is the difference between recursion and iteration? When would you use each?' },
    { id: 'dsa_24', text: 'How would you solve the two sum problem?' },
    { id: 'dsa_25', text: 'Describe the algorithm for reversing a linked list.' },
    { id: 'dsa_26', text: 'What is backtracking and give an example problem?' },
    { id: 'dsa_27', text: 'Explain the Floyd\'s cycle detection algorithm.' },
    { id: 'dsa_28', text: 'What are segment trees and their use cases?' },
    { id: 'dsa_29', text: 'Explain the concept of sliding window technique.' },
    { id: 'dsa_30', text: 'What is the Knapsack problem and its variations?' },
    // Advanced DSA (31-45)
    { id: 'dsa_31', text: 'Explain the concept of suffix arrays.' },
    { id: 'dsa_32', text: 'What is the Fenwick tree and how is it used?' },
    { id: 'dsa_33', text: 'Describe the A* search algorithm.' },
    { id: 'dsa_34', text: 'Explain the concept of bloom filters.' },
    { id: 'dsa_35', text: 'What is the difference between DFS and BFS in terms of space and time complexity?' },
    { id: 'dsa_36', text: 'Describe the Bellman-Ford algorithm.' },
    { id: 'dsa_37', text: 'Explain the concept of minimum spanning trees.' },
    { id: 'dsa_38', text: 'What is the difference between Kruskal\'s and Prim\'s algorithm?' },
    { id: 'dsa_39', text: 'Describe the concept of union-find data structure.' },
    { id: 'dsa_40', text: 'Explain the KMP algorithm for string matching.' },
    { id: 'dsa_41', text: 'What is the Rabin-Karp algorithm?' },
    { id: 'dsa_42', text: 'Describe the concept of Z-algorithm for pattern matching.' },
    { id: 'dsa_43', text: 'Explain the concept of convex hull.' },
    { id: 'dsa_44', text: 'What is the difference between strong and weak connectivity in graphs?' },
    { id: 'dsa_45', text: 'Describe Tarjan\'s algorithm for finding strongly connected components.' },
    // Problem Solving (46-55)
    { id: 'dsa_46', text: 'How would you merge k sorted arrays?' },
    { id: 'dsa_47', text: 'Explain the approach to solving the subset sum problem.' },
    { id: 'dsa_48', text: 'How would you find the shortest path in a graph with negative weights?' },
    { id: 'dsa_49', text: 'Describe the solution to the word ladder problem.' },
    { id: 'dsa_50', text: 'How would you solve the median of two sorted arrays problem?' },
    { id: 'dsa_51', text: 'Explain the approach to solving the longest palindromic substring problem.' },
    { id: 'dsa_52', text: 'How would you solve the maximum rectangle problem?' },
    { id: 'dsa_53', text: 'Describe the solution to the trapping rain water problem.' },
    { id: 'dsa_54', text: 'How would you implement a autocomplete system using a trie?' },
    { id: 'dsa_55', text: 'Explain the approach to solving the regular expression matching problem.' },
  ],

  behavioral: [
    // Conflict & Teamwork (1-15)
    { id: 'behav_1', text: 'Tell me about a time you had a conflict with a colleague and how you resolved it.' },
    { id: 'behav_2', text: 'Describe a situation where you had to work with someone you didn\'t get along with.' },
    { id: 'behav_3', text: 'Tell me about a time you had to give constructive feedback to a peer.' },
    { id: 'behav_4', text: 'Describe your experience with collaborative problem-solving.' },
    { id: 'behav_5', text: 'Tell me about a time you had to compromise in a team decision.' },
    { id: 'behav_6', text: 'How do you contribute to a positive team environment?' },
    { id: 'behav_7', text: 'Describe a time you had to support a colleague during a challenging period.' },
    { id: 'behav_8', text: 'Tell me about a time you had to work in a diverse team.' },
    { id: 'behav_9', text: 'Describe your experience with team building activities.' },
    { id: 'behav_10', text: 'Tell me about a time you had to adapt your communication style for different audiences.' },
    { id: 'behav_11', text: 'How do you handle working with a colleague who has a different work style?' },
    { id: 'behav_12', text: 'Describe a time you had to trust a colleague with an important task.' },
    { id: 'behav_13', text: 'Tell me about a time you felt excluded in a team.' },
    { id: 'behav_14', text: 'Describe a situation where you had to be a team player.' },
    { id: 'behav_15', text: 'Tell me about a time you received recognition for teamwork.' },
    // Initiative & Innovation (16-30)
    { id: 'behav_16', text: 'Describe a time you took initiative to improve a process.' },
    { id: 'behav_17', text: 'Tell me about an innovative idea you proposed at work.' },
    { id: 'behav_18', text: 'Describe a time you went beyond your job description.' },
    { id: 'behav_19', text: 'Tell me about a project you started from scratch.' },
    { id: 'behav_20', text: 'Describe a time you had to learn a new skill quickly to complete a project.' },
    { id: 'behav_21', text: 'Tell me about a time you identified a problem and took action.' },
    { id: 'behav_22', text: 'Describe a situation where you improved efficiency in your team.' },
    { id: 'behav_23', text: 'Tell me about a time you proposed a solution that was implemented.' },
    { id: 'behav_24', text: 'Describe a time you had to be creative to solve a problem.' },
    { id: 'behav_25', text: 'Tell me about a time you took ownership of a difficult task.' },
    { id: 'behav_26', text: 'Describe a time you implemented feedback you received.' },
    { id: 'behav_27', text: 'Tell me about a time you had to break a bad habit or process.' },
    { id: 'behav_28', text: 'Describe your experience with continuous improvement.' },
    { id: 'behav_29', text: 'Tell me about a time you helped train a new employee.' },
    { id: 'behav_30', text: 'Describe a time you had to challenge the status quo.' },
    // Resilience & Learning (31-45)
    { id: 'behav_31', text: 'Tell me about a time you failed and what you learned from it.' },
    { id: 'behav_32', text: 'Describe a situation where you had to persevere through a difficult project.' },
    { id: 'behav_33', text: 'Tell me about a time you had to ask for help.' },
    { id: 'behav_34', text: 'Describe a time you had to recover from a professional setback.' },
    { id: 'behav_35', text: 'Tell me about a time you had to deal with ambiguity.' },
    { id: 'behav_36', text: 'Describe a situation where you had to work with limited resources.' },
    { id: 'behav_37', text: 'Tell me about a time you had to pivot your approach.' },
    { id: 'behav_38', text: 'Describe a time you had to work outside your comfort zone.' },
    { id: 'behav_39', text: 'Tell me about a time you had to handle multiple competing priorities.' },
    { id: 'behav_40', text: 'Describe a situation where you had to deliver under pressure.' },
    { id: 'behav_41', text: 'Tell me about a time you had to learn from criticism.' },
    { id: 'behav_42', text: 'Describe a time you had to overcome self-doubt.' },
    { id: 'behav_43', text: 'Tell me about a time you had to stay calm under pressure.' },
    { id: 'behav_44', text: 'Describe a situation where you had to deal with an angry customer or stakeholder.' },
    { id: 'behav_45', text: 'Tell me about a time you had to adapt your plan due to unforeseen circumstances.' },
    // Leadership & Influence (46-55)
    { id: 'behav_46', text: 'Describe a time you had to influence others without formal authority.' },
    { id: 'behav_47', text: 'Tell me about a time you had to make a difficult decision with incomplete information.' },
    { id: 'behav_48', text: 'Describe a situation where you had to motivate your team.' },
    { id: 'behav_49', text: 'Tell me about a time you had to lead by example.' },
    { id: 'behav_50', text: 'Describe a time you had to delegate tasks effectively.' },
    { id: 'behav_51', text: 'Tell me about a time you had to have a difficult conversation.' },
    { id: 'behav_52', text: 'Describe a situation where you had to make unpopular decisions.' },
    { id: 'behav_53', text: 'Tell me about a time you had to build trust quickly with a new team.' },
    { id: 'behav_54', text: 'Describe your vision for your ideal leadership style.' },
    { id: 'behav_55', text: 'Tell me about a time you had to coach someone who was struggling.' },
  ],

  communication: [
    // Presentation & Public Speaking (1-15)
    { id: 'comm_1', text: 'Tell me about your experience with public speaking or presentations.' },
    { id: 'comm_2', text: 'How do you prepare for an important presentation?' },
    { id: 'comm_3', text: 'Describe a time you had to present complex information to a non-technical audience.' },
    { id: 'comm_4', text: 'Tell me about a time your presentation resulted in a successful outcome.' },
    { id: 'comm_5', text: 'How do you handle difficult questions during a presentation?' },
    { id: 'comm_6', text: 'Describe your approach to storytelling in business communication.' },
    { id: 'comm_7', text: 'Tell me about a time you had to communicate bad news.' },
    { id: 'comm_8', text: 'How do you tailor your communication style for different audiences?' },
    { id: 'comm_9', text: 'Describe a time you had to use visual aids effectively in communication.' },
    { id: 'comm_10', text: 'Tell me about your experience with written communication.' },
    { id: 'comm_11', text: 'How do you handle miscommunication in a team?' },
    { id: 'comm_12', text: 'Describe a time you had to communicate across different departments.' },
    { id: 'comm_13', text: 'Tell me about a time you had to persuade others through communication.' },
    { id: 'comm_14', text: 'How do you ensure clarity in your written documents?' },
    { id: 'comm_15', text: 'Describe your experience with email communication.' },
    // Listening & Empathy (16-30)
    { id: 'comm_16', text: 'Tell me about a time you had to listen carefully to understand someone\'s concerns.' },
    { id: 'comm_17', text: 'How do you show empathy in your professional interactions?' },
    { id: 'comm_18', text: 'Describe a time you had to have a difficult conversation with empathy.' },
    { id: 'comm_19', text: 'Tell me about a time you had to understand a client\'s needs through careful listening.' },
    { id: 'comm_20', text: 'How do you handle interruptions and stay focused on the speaker?' },
    { id: 'comm_21', text: 'Describe a time you had to ask clarifying questions to understand better.' },
    { id: 'comm_22', text: 'Tell me about a time you changed your mind based on someone\'s perspective.' },
    { id: 'comm_23', text: 'How do you demonstrate active listening in meetings?' },
    { id: 'comm_24', text: 'Describe a time you had to validate someone\'s concerns even when you disagreed.' },
    { id: 'comm_25', text: 'Tell me about a time you had to adjust your message based on feedback.' },
    { id: 'comm_26', text: 'How do you ensure you are being understood in important conversations?' },
    { id: 'comm_27', text: 'Describe a time you had to bridge a communication gap.' },
    { id: 'comm_28', text: 'Tell me about your experience with one-on-one communication.' },
    { id: 'comm_29', text: 'How do you provide feedback in a constructive way?' },
    { id: 'comm_30', text: 'Describe a time you had to communicate through multiple channels.' },
    // Remote & Digital Communication (31-45)
    { id: 'comm_31', text: 'How do you stay connected with your team in a remote environment?' },
    { id: 'comm_32', text: 'Describe a time you had to conduct an effective virtual meeting.' },
    { id: 'comm_33', text: 'Tell me about your experience with asynchronous communication.' },
    { id: 'comm_34', text: 'How do you maintain communication clarity when working remotely?' },
    { id: 'comm_35', text: 'Describe a time you had to build rapport through digital communication.' },
    { id: 'comm_36', text: 'Tell me about your experience with video conferencing tools.' },
    { id: 'comm_37', text: 'How do you handle time zone differences in team communication?' },
    { id: 'comm_38', text: 'Describe a time you had to document and share knowledge digitally.' },
    { id: 'comm_39', text: 'Tell me about your experience with instant messaging platforms.' },
    { id: 'comm_40', text: 'How do you avoid misunderstandings in written digital communication?' },
    { id: 'comm_41', text: 'Describe a time you had to facilitate a remote brainstorming session.' },
    { id: 'comm_42', text: 'Tell me about your experience managing communication overload.' },
    { id: 'comm_43', text: 'How do you ensure important information doesn\'t get lost in communication?' },
    { id: 'comm_44', text: 'Describe a time you had to use tools to improve team communication.' },
    { id: 'comm_45', text: 'Tell me about your experience with hybrid team communication.' },
    // Stakeholder Communication (46-55)
    { id: 'comm_46', text: 'How do you communicate with stakeholders at different levels?' },
    { id: 'comm_47', text: 'Describe a time you had to manage expectations through communication.' },
    { id: 'comm_48', text: 'Tell me about your experience with status updates and progress reporting.' },
    { id: 'comm_49', text: 'How do you communicate risks and issues to stakeholders?' },
    { id: 'comm_50', text: 'Describe a time you had to get buy-in for your ideas through communication.' },
    { id: 'comm_51', text: 'Tell me about your experience with cross-cultural communication.' },
    { id: 'comm_52', text: 'How do you balance transparency with discretion in communication?' },
    { id: 'comm_53', text: 'Describe a time you had to communicate a change to your team.' },
    { id: 'comm_54', text: 'Tell me about your experience with external communication.' },
    { id: 'comm_55', text: 'How do you measure the effectiveness of your communication?' },
  ],

  resume: [
    // Resume-based follow-ups
    { id: 'resume_1', text: 'Tell me more about the technologies and tools you used in this project.' },
    { id: 'resume_2', text: 'What was your specific contribution to this achievement?' },
    { id: 'resume_3', text: 'How did you measure the success of this project?' },
    { id: 'resume_4', text: 'What challenges did you face during this project and how did you overcome them?' },
    { id: 'resume_5', text: 'If you could do this project again, what would you do differently?' },
    { id: 'resume_6', text: 'How did you collaborate with your team members on this project?' },
    { id: 'resume_7', text: 'What was the impact of this project on the company or users?' },
    { id: 'resume_8', text: 'What did you learn from this experience?' },
    { id: 'resume_9', text: 'Can you explain the technical architecture of this system you built?' },
    { id: 'resume_10', text: 'How would you improve the solution you developed?' },
    { id: 'resume_11', text: 'What was your role in the team and how did you interact with other team members?' },
    { id: 'resume_12', text: 'How did you handle conflicting requirements or feedback on this project?' },
    { id: 'resume_13', text: 'What tools or frameworks did you use and why did you choose them?' },
    { id: 'resume_14', text: 'How did you approach testing and quality assurance for this project?' },
    { id: 'resume_15', text: 'What was the timeline for this project and how did you manage it?' },
    { id: 'resume_16', text: 'Can you walk me through your decision-making process for this project?' },
    { id: 'resume_17', text: 'What was the most challenging part of this project?' },
    { id: 'resume_18', text: 'How did you ensure code quality and maintainability in this project?' },
    { id: 'resume_19', text: 'What metrics or KPIs did you track for this project?' },
    { id: 'resume_20', text: 'How did you handle requirements changes during this project?' },
    { id: 'resume_21', text: 'Tell me about the stakeholders involved in this project.' },
    { id: 'resume_22', text: 'How did you ensure the project stayed on schedule and budget?' },
    { id: 'resume_23', text: 'What was your experience with version control and collaborative development?' },
    { id: 'resume_24', text: 'How did you document your work for this project?' },
    { id: 'resume_25', text: 'What would you highlight as your best work from this project?' },
  ]
};

// Export for use in interview system
if (typeof module !== 'undefined' && module.exports) {
  module.exports = { enhancedQuestionBank };
}
